### ISSUE TITLE
Caching Authentication

### ISSUE THREAD

**Issue by poindexter12** [hjdhjd/unifi-protect#14]
**Is your feature request related to a problem? Please describe:**
Cache authentication as necessary to avoid hitting new unifi rate limiting constraint where possible.

**Describe the solution you'd like:**
Ability to selectively use existing authentication credentials which can be overridden as needed.

**Describe alternatives you've considered:**
Updating unifi settings which does work but is likely not accessible to all users.

**Additional context:**
Thanks Ubiquiti. [https://community.ui.com/questions/Unifi-API-Rate-Limited/ba82a718-9418-46b0-8f2f-235bfc647f9b](https://community.ui.com/questions/Unifi-API-Rate-Limited/ba82a718-9418-46b0-8f2f-235bfc647f9b)

**Comment by hjdhjd** [comment]
Thanks…as stated elsewhere, I will likely add this in the future, but well-behaved consumers of this API shouldn’t need to reauthenticate frequently, if ever, in a given session/instance.

Thanks for raising it!
