### ISSUE TITLE
Improve snapshot quality (lower compression) / export still picture from stream?

### ISSUE THREAD

**Issue by mrandt** [hjdhjd/unifi-protect#19]
**Is your feature request related to a problem? Please describe:**

I bought a UVC-G5-Pro and mounted it to the tower of my flying club's airfield. We primarily want to use it as a "netcam" and upload a picture once a minute to our website, for pilots to judge weather condition or just admire the glider planes ;-)

This seems awkwardly difficult to achieve. The "anonymous snapshot" feature of the cam itself only returns 640px width and very highly compressed images - bummer.

I started researching and found no easy way to export still pictures from Unifi Protect nor the cam.

Finally, I came across this library. Thanks a lot for making this! I learned enough NodeJS to get it to call the "getSnapshot" via Unifi Protect API last night.

Now I can obtain 3840x2160 px resolution snapshot, but the pictures are still heavily compressed and look terrible...

**Describe the solution you'd like:**

I would liked to reduce JPEG compression on the getSnapshot returned image - or set it to a higher quality at least.

I am unsure if Unifi has necessary parameters, fiddling with the UI I could not find any. For playback it seems multiple channels with different compressions are supported, but I was not successful applying those params to the snapshot endpoint.

**Describe alternatives you've considered:**

If Unifi Protect snapshot endpoint does in fact not provide better quality image, an alternative approach might be to extract a higher quality still picture from the video stream. But I honestly don't know how to do that.

Maybe a convienience method could be added to the stream API?

**Additional context:**

I am attaching two JPEG show the problem. One was obtained through snapshot service, the other was exported from Unifi Protect UI. You also see a big difference in file size.

Snapshot:

![snapshot_from_API](https://github.com/hjdhjd/unifi-protect/assets/10500490/eb3aff9b-66fe-40a0-a1eb-449a1da61524)

Still picture taken from Unifi Protect UI:

![still_picture_taken_from_Unifi_Protect_UI](https://github.com/hjdhjd/unifi-protect/assets/10500490/e71d7fc9-22f7-4418-b8fc-04fd02bed39b)

**Comment by mrandt** [comment]
I was in contact with Unifi. As the API is not intended for 3rd party use, they would not comment on parameters / usage.

Also, they could not tell me wether they would "fix" the anonymous snapshot. 

I have posted a feature request to Unifi community forums, asking for a feature to expose still pictures in configurable resolution / compression.

Read it here - maybe you care to "upvote"?

https://community.ui.com/questions/Feature-Request-Export-still-static-pictures-from-Unifi-Protect-e-g-for-webcam-website-integration/7be6eaea-03af-4a5a-bc7e-4c0f22b8ebd6

@hjdhjd Would you have any pointers as to how I could use the video stream and extract a single frame / still picture with your API client? Greatly appreciated!

**Comment by mrandt** [comment]
Sorry, did not intend to close.

**Comment by hjdhjd** [comment]
Thanks for the request - I'll look into this as time allows in the near future, but I'm closing for this one for the time being. I'm certainly interested in improving snapshot quality...I appreciate you doing some homework to track down some of the detail of this. I'll be looking to incorporate this soon.
