### ISSUE TITLE
No able to login

### ISSUE THREAD

**Issue by jo0zt** [hjdhjd/unifi-protect#20]
**Describe The Problem:**
Since last week I cannot login to the protect integration. Until then I used a cloud account and everything was fine. This time I made a local account and get the same error everytime I try to login (see screenshot). 
I have the latest versions of all apps, home assistant, UniFi protect and the integration and a local account (created like the files suggested)with all access to the protect app. 

**To Reproduce:**

**Logs:**
N/a

```
Show the UniFi Protect API logs here.
Remove any sensitive information.
```

**Screenshots:**
![image](https://github.com/hjdhjd/unifi-protect/assets/100353862/b817357c-d2f5-46bd-9989-6997f66dd65b)<!— If applicable, add screenshots to help explain your problem. —>

**Comment by hjdhjd** [comment]
Unfortunately, your issue relates to HomeAssistant, not this project. This is the underlying library that provides Protect API access. It’s a technical project for developers to use in building their solutions. I would suggest you try to open an issue on the HomeAssistant Github. Best of luck.
