### ISSUE TITLE
Feature Request: getThumbnail and getThumbnailAnimated

### ISSUE THREAD

**Issue by Scrounger** [hjdhjd/unifi-protect#24]
**Is your feature request related to a problem? Please describe:**
First thanks a lot for this great library, great work !

**Describe the solution you'd like:**
Can you please implement a function to download the thumbnails?

Endpoint for this are:

/proxy/protect/api/events/#eventId#/thumbnail?h=266.5625&w=266.5625 Thumbnail
/proxy/protect/api/events/#eventId#/animated-thumbnail?h=149.94140625&keyFrameOnly=true&speedup=10&w=266.5625 animated Thumbnail

EventId can be taken from an event with "modelKey": "event". Parameters seems to be optional

My wish is to have a function where i can pass the eventId as parameter. Perhaps two function, one for Thumbnail and one for Small Thumbnail.

**Describe alternatives you've considered:**
see above

**Additional context:**
Could you please implement this?

**Comment by hjdhjd** [comment]
You can do this yourself...to either access individual [snapshots](https://github.com/hjdhjd/unifi-protect/blob/main/docs/ProtectApi.md#getsnapshot) or [or execute arbitrary calls to the API](https://github.com/hjdhjd/unifi-protect/blob/main/docs/ProtectApi.md#retrieve).

Please read the documentation before opening an issue or creating a request. Thanks!

**Comment by Scrounger** [comment]
ah that's great.
I read your very good documentation diligently, but I missed the `retrieve()` function, thanks for your support!

**Comment by hjdhjd** [comment]
Enjoy! It's a very mature library at this point and used in several other projects.

**Comment by hjdhjd** [comment]
I also corrected the documentation for retrieve - there was a paste-error there. 😄
