### ISSUE TITLE
Feature Request: make login credentials accessible

### ISSUE THREAD

**Issue by Scrounger** [hjdhjd/unifi-protect#25]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Can you please make the currently valid login credentials (X-CSRF-Token, Cookie, etc.) accessible or the complete header.
So it would be possible to use the established connection, to get some custom stuff, e.g. downloading thumbnails #24

**Describe alternatives you've considered:**
see above

**Additional context:**
none

**Comment by hjdhjd** [comment]
You can already get thumbnails through the API, as well as send arbitrary requests. The whole point of the library is to abstract away that stuff so you just tell it what you want to do. 😄 

TL;DR: not planning to implement it because it's redundant with the functionality that already exists.
