### ISSUE TITLE
prometheus exporter

### ISSUE THREAD

**Issue by lZzozZl** [hjdhjd/unifi-protect#30]
**Is your feature request related to a problem? Please describe:**

am for me is a problem. I need data from my unifi protect to my prometheus so i can use grafana to show metrics ( cameras, nvr )
**Describe the solution you'd like:**

An exporter which can be run on debian12 and can collect all the api information from the unifi protect and store it into prometheus host so i can than make a grafana dashboard.
**Describe alternatives you've considered:**

Nothing else. I try to find such a tool but without success 
**Additional context:**

**Comment by hjdhjd** [comment]
This is a library meant for use by developers, not an end user tool. You’re on your own to build things using it. Best of luck.

**Comment by lZzozZl** [comment]
Thank you for responding :)
