### ISSUE TITLE
Sending event information TO Protect.... what are the options?

### ISSUE THREAD

**Issue by HostGrabs** [hjdhjd/unifi-protect#33]
**Is your feature request related to a problem? Please describe:**
Lock-in.  Interoperability.  Hardware functionality.

**Describe the solution you'd like:**
I'd like to see the world get along.  Or at the bare minimum, my electronics.  It's all JSON event information at the end of the day, right?  I've got non-Ubiquiti devices that I'd like to have communicate with Protect as seamlessly as possible, will the controller accept event information from non-Ubiquiti devices, or can it be tricked to do so?

**Describe alternatives you've considered:**
Going whole-hog and committing to the Ubiquiti ecosystem... single point of failure!
Ditching Ubiquiti entirely.....  but we've already got some, and pricing is decent!
Resigning to a patchwork here-there-and-everywhere approach.... not if I can help it!

**Additional context:**
I've never played with event notification type things before, nor the UniFi API (props for reverse engineering it, btw, that's impressive) but I'm damned if I'm going to limit myself to their hardware options if there's any chance I can use the toys I want and centralize their management, too!  All to say, I might be asking a really stupid sounding question that had I any clue what I was looking at I'd have been able to figure out the answer out on my own...  please forgive me!  I'm not asking for the legwork, just a reality check.   Could it maybe be done with enough finagling?

Specific example, if it helps.  The AXIS P3265-LVE-3 has onboard LPC/LPR functionality and can be configured to send JSON TCP or HTTP POST event information to one or more servers.  Ubiquiti's AI cameras can also do LPC, and one would hope LPR (their documentation as a whole leaves a lot to be desired!)  so theoretically, one would hope Protect could collect the same data in the same fashion, despite one device being 3rd party.

**Comment by hjdhjd** [comment]
Thanks for the request, but I'm afraid there's nothing here for me to work with/on. This is an API interface into the UniFi Protect controller...that's it. You build applications using it to communicate with the Protect controller. If you'd like to emulate the controller itself, this is not the library you're looking for, nor do I have any plans to do so. The scope of this library is to provide a well-defined Node/JS API to a UniFi Protect controller.

Best of luck!
