### ISSUE TITLE
PTZ Camera Preset Control

### ISSUE THREAD

**Issue by dhruvb14** [hjdhjd/unifi-protect#41]
**Is your feature request related to a problem? Please describe:**

I have a G5 PTZ camera with a few saved presets which I would like to be able to quickly toggle to. So I can setup a Kiosk viewing this one camera and jump between preset views. I am not looking for full PTZ control but instead jump to presets. 
**Describe the solution you'd like:**

Upon investigation into the rest calls made to control presets this is how it works. I was able to successfully control positions via a curl commands. I am hoping to expose a button which can be toggled on/off to toggle between preset number when on and reset (-1) when off.
###  Return To Home Position
```
curl 'https://192.168.100.1/proxy/protect/api/cameras/{{CAMERA_GUID}}/ptz/goto/-1' \
  -X 'POST' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-length: 0' \
  -H 'cookie: TOKEN={{API_TOKEN}}' \
  -H 'origin: https://192.168.100.1'
```
### Preset 1 (GUI Shows 1 but array position 0)
# Return To Home Position
```
curl 'https://192.168.100.1/proxy/protect/api/cameras/{{CAMERA_GUID}}/ptz/goto/0' \
  -X 'POST' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-length: 0' \
  -H 'cookie: TOKEN={{API_TOKEN}}' \
  -H 'origin: https://192.168.100.1'
```
**Describe alternatives you've considered:**

Attempted Guided access mode on iPhone viewer using Protect application (Too much room for error) and same thing on Android using Fully Kiosk Mode.

You can see my presets which were created in the GUI in the photo below
<img width="1010" alt="Screenshot 2024-11-23 at 1 31 29 PM" src="https://github.com/user-attachments/assets/218285d0-a302-4de1-819c-fb47d41eff6b">

**Additional context:**

**Comment by hjdhjd** [comment]
Appreciate the request, but it doesn't belong here.

This is a low-level library to access the UniFi Protect API. You are welcome to use it to implement the functionality you're looking for, but it's not intended for use as an end user application. 

**This is a lower-level Node-native API to access UniFi Protect, not an end-user application.**

**Comment by dhruvb14** [comment]
@hjdhjd I understand this is a low level library. This PTZ control is not exposed in the current API class and I was hoping to expose it so I can use this library to control PTZ Cameras. Implementation and usage could be done in `homebridge-unifi-protect` which you manage but this has to be implemented first no?

I tried to look though the `protect-api.ts` and didn't see a way to make a generic rest call with Auth attached.

I understand you probably get lots of requests and I do not mind doing the work but I honestly thought this is where the low level calls should happen then the consumer `homebridge-unifi-protect` would expose a switch to control the camera. Could you point me to where in `homebridge-unifi-protect` you think the implementation for something like this would happen if not via this low level library?

**Comment by hjdhjd** [comment]
You can make any call you want using this library. Nothing further needs to be implemented here, almost by definition of it being a low-level library. 😄

The documentation is your friend. See the [retrieve](https://github.com/hjdhjd/unifi-protect/blob/main/docs/ProtectApi.md#retrieve) method.

Beyond that, I would point you to spending meaningful time understanding HBUP. 😄 No, **nothing** needs to be implemented in this library to support PTZ. PTZ isn’t supported in HBUP because it’s been a third-class citizen in Protect until recently. Some stuff will come there at some point, it’s just not a priority…but it has nothing to do with this library.
