### ISSUE TITLE
TypeScript type exports for real-time updates

### ISSUE THREAD

**Issue by niobos** [hjdhjd/unifi-protect#5]
**Is your feature request related to a problem? Please describe:**
I'm trying to interface with this unifi-protect library from TypeScript. Based on [an example](https://github.com/hjdhjd/homebridge-unifi-protect/blob/2b464fb6b190b7a30c93a5f79abb0b4f754a5a21/src/protect-nvr-events.ts#L163), I learned that I need to decode the binary websocket messages into a `ProtectNvrUpdatePacket`. However, that particular type does not seems to be exported. It's not exported from [protect-api-updates.ts](https://github.com/hjdhjd/unifi-protect/blob/main/src/protect-api-updates.ts#L108), and I can't find a more generic type in other locations either.
Just for clarity: this is purely a type export issue; the code seems to function just fine. **This is a minor issue.**

**Describe the solution you'd like:**
export some type that can be used for decoding update packets. I don't know if it needs to be this exact type as defined in protect-api-updates.ts, or some more generic type.

**Describe alternatives you've considered:**
Working with untyped code works, but isn't ideal.

**Additional context:**
none

**Comment by hjdhjd** [comment]
There'll be an upcoming major release that actually eliminates the entire need for this...stay tuned! Really appreciate the request though!
